### ISSUE TITLE
如何在同一个div中反复渲染不同脑图

### ISSUE THREAD

**Issue by liuhao1234** [hizzgdev/jsmind#208]
页面初次渲染
![WX20190820-144645](https://user-images.githubusercontent.com/16381184/63323861-5c539d00-c359-11e9-9156-6a7102daa3c4.png)
页面切换脑图
![WX20190820-144722](https://user-images.githubusercontent.com/16381184/63323888-6f666d00-c359-11e9-8c19-bb39ef70406e.png)
页面初始化正常，但是切换脑图重新渲染是出现错误，以下是项目代码，有解决办法么，jsmind有没有destroy方法
![WX20190820-144834](https://user-images.githubusercontent.com/16381184/63324031-bfddca80-c359-11e9-8946-d91c4dc15c79.png)
![WX20190820-144904](https://user-images.githubusercontent.com/16381184/63324040-c66c4200-c359-11e9-8a20-24f742f79e10.png)

**Comment by hizzgdev** [comment]
不要重复的new jsMind()就行了，同一个div只使用同一个实例即可。

**Comment by wind-answer** [comment]
您好，我在页面的同一个div中每次根据条件的不同会到数据库中取不同的mind数据，取是取回来了，但是这个实例好像每次只是在这个div中添加新的脑图，旧的mind数据也不删除，请问怎样删除旧的mind数据

**Comment by hizzgdev** [comment]
不要重复的new，要重复的show()

**Comment by wind-answer** [comment]
我就没new过，哭了
let fetchMindUrl = localhostPath + projectName + "/CXF/REST/Domain/jsmindOpen/"
		$.ajax({
			async : false,
			cache : false,
			type : 'GET',
			url : fetchMindUrl + documentID,
			dataType : 'json',
			success : function(response) {
				$("#jsmind_container").css("display", "block")
				documentID = -1
				var mind = {
					meta : {
						name : 'demo',
						author : 'hizzgdev@163.com',
						version : '0.2'
					},
					format : 'node_array',
					data : JSON.parse(response.content),
				};
				var options = {
					container : 'jsmind_container' ,
					editable : true,
					theme : 'primary',
					mode : 'side',
					view : {
						hmargin : 100,
						vmargin : 9,
					},
					shortcut : {
						handles : {
							test : function(j, e) {
								console.log(j);
							}
						},
						mapping : {
							test : 89
						}
					}
				}
				_jm = jsMind.show(options,mind);
			},
			error : function() {
				alert("取图失败！")
			}

**Comment by wind-answer** [comment]
可以加您微信详细询问一下嘛，万分感谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhigang Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 下午3:51
收件人:&nbsp;"hizzgdev/jsmind"<jsmind@noreply.github.com&gt;;
抄送:&nbsp;"活宝"<306419051@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hizzgdev/jsmind] 如何在同一个div中反复渲染不同脑图 (#208)



不要重复的new，要重复的show() 
 
 &gt; 在 2020年1月9日，15:22，wind-answer <notifications@github.com&gt; 写道： 
 &gt;  
 &gt; ﻿ 
 &gt; 您好，我在页面的同一个div中每次根据条件的不同会到数据库中取不同的mind数据，取是取回来了，但是这个实例好像每次只是在这个div中添加新的脑图，旧的mind数据也不删除，请问怎样删除旧的mind数据 
 &gt;  
 &gt; — 
 &gt; You are receiving this because you commented. 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hizzgdev** [comment]
https://github.com/hizzgdev/jsmind/blob/master/docs/zh/1.usage.md


用1.1里的方法，只new一次，后面使用这个new出来的对象不断的重复show就行了。

怪我教了大家用jsMind.show这个方法，你在哪里看到的？我回头给改过来。

**Comment by wind-answer** [comment]
万分感谢大佬！！！刚刚我把_jm new到判断分支了，只要执行一次判断他就会new一次，我太垃圾了。还有jsMind.show(options,mind)这个方法是在您的demo.html和features.html里面都有的

**Comment by hizzgdev** [comment]
好，我抽空也给改回来。

**Comment by xiaozzhou** [comment]
今天也用到多个图的需求,作者能否改成周期组件呢?能注销实例和建多个不同实例相互不影响,用目前的代码虽然能多个实例,但是发现监听事件会重复的
